image:
  repository: linuxserver/sonarr
  pullPolicy: IfNotPresent
  # Version Tags
  # Stable releases from Sonarr (currently v2)
  # Preview releases from Sonarr (currently v3)
  tag: arm64v8-3.0.6.1196-ls100

strategy:
  type: Recreate

env:
  TZ: "Europe/London"

service:
  type: ClusterIP
  port:
    port: 8989
    # port: 80 It doesn't work with this port for some reason

ingress:
  enabled: false

probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      exec:
        command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
          read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    emptyDir: false
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    existingClaim: "media-config-ssd-claim"
    subPath: "configs/sonarr"
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
  media:
    enabled: true
    emptyDir: false
    mountPath: /media
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    existingClaim: "media-ssd-claim"
    # subPath: "movies"
    accessMode: ReadWriteOnce
    size: 10Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
