sonarr:
  image:
    organization: linuxserver
    repository: sonarr
    pullPolicy: IfNotPresent
    tag: arm64v8-3.0.4.993-ls70
  env:
    TZ: "Europe/London"
  service:
    type: ClusterIP
    port: 8989
    # port: 80 It doesn't work with this port for some reason
  persistence:
    config:
      enabled: true
      ## If you want to reuse an existing claim, you can pass the name of the PVC using
      ## the existingClaim variable
      existingClaim: "media-config-ssd-claim"
      subPath: "configs/sonarr"
      accessMode: ReadWriteOnce
      size: 1Gi
      ## Do not delete the pvc upon helm uninstall
      skipuninstall: false
    media:
      enabled: true
      ## If you want to reuse an existing claim, you can pass the name of the PVC using
      ## the existingClaim variable
      existingClaim: "media-ssd-claim"
      # subPath: "movies"
      accessMode: ReadWriteOnce
      size: 10Gi
      ## Do not delete the pvc upon helm uninstall
      skipuninstall: false
