---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-config-ssd-volume"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "30Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/media"
---
