---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "media"
  name: "media-ingress"
spec:
  rules:
  - host: "media.192.168.0.240.nip.io"
    http:
      paths:
        - path: "/transmission"
          pathType: Prefix
          backend:
            service:
              name: "transmission-transmission-openvpn"
              port:
                number: 80
        - path: "/jackett"
          pathType: Prefix
          backend:
            service:
              name: "jackett"
              port:
                number: 9117
        - path: "/sonarr"
          pathType: Prefix
          backend:
            service:
              name: "sonarr"
              port:
                number: 8989
        - path: "/radarr"
          pathType: Prefix
          backend:
            service:
              name: "radarr"
              port:
                number: 7878
        - path: "/lidarr"
          pathType: Prefix
          backend:
            service:
              name: "radarr"
              port:
                number: 8686
        - path: "/ombi"
          pathType: Prefix
          backend:
            service:
              name: "ombi"
              port:
                number: 3579
        - path: "/tautulli"
          pathType: Prefix
          backend:
            service:
              name: "tautulli"
              port:
                number: 8181
        - path: "/flood"
          pathType: Prefix
          backend:
            service:
              name: "flood"
              port:
                number: 3000
        - path: "/youtubedl"
          pathType: Prefix
          backend:
            service:
              name: "youtubedl-youtubedl-material"
              port:
                number: 17442
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: "plex-tcp"
              port:
                number: 32400
---
