{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lazylibrarian.serviceAccountName" . }}
  labels:
    {{- include "lazylibrarian.labels" . | nindent 4 }}
{{- end -}}
