#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: arm64v8-version-v0.20.1796

strategy:
  type: Recreate

env:
  TZ: "Europe/London"

# service:
#   type: ClusterIP
#   port:
#     port: 9117
#     # port: 80 It doesn't work with this port for some reason

# ingress:
#   enabled: false

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 9117

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: true
    emptyDir: false
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    existingClaim: "media-config-ssd-claim"
    subPath: "configs/jackett"
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false

  torrentblackhole:
    enabled: false
    emptyDir: false
    mountPath: /downloads
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""
