version: "3.8"

services:
  # Jackett
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./jackett-config:/config
      - ./media-storage/Downloads/completed:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.home`)"

  # Sonarr
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./sonarr-config:/config
      - ./media-storage/Downloads/completed:/data/completed
      - ./media-storage/Episodes:/episodes
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - transmission
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.home`)"

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./bazarr-config:/config
      - ./media-storage/Episodes:/episodes
    depends_on:
      - jackett
      - transmission
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.home`)"

  # Transmission
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./protonvpn/:/etc/openvpn/custom/
      - ./transmission-config/config:/config
      - ./media-storage/Downloads:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .vpn
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=ro-16.protonvpn.udp
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "9091:9091"
      # - '9117:9117'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.home`)"

  # Traefik reverse proxy e.g. jellyfin.home -> localhost:8096
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "9090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
