---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "services"
  name: "calibre-data-pvc"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Gi"
---
