image:
  repository: linuxserver/calibre-web
  tag: arm64v8-0.6.11-ls109
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

env:
  TZ: "Europe/London"
  PUID: 1001
  PGID: 1001
  UMASK: 22
  # Linuxserver.io additional layers.
  # Enables additional features for the image, at the cost of increased size and
  # possible incompatabilities with certain architectures. Disabled by default.
  DOCKER_MODS:
    # Enable ebook conversion. Compatible with x86_64 image only.
    # To enable, set enabled to true, and follow the guide at: https://github.com/linuxserver/docker-calibre-web#application-setup
    # to configure the application.
    ebookConversion:
      enabled: true
      image:
        repository: linuxserver/calibre-web
        # To use a different tag for the DockerMod, specify the tag below
        tag: calibre

service:
  type: ClusterIP
  port:
    port: 80
    # port: 8083

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: calibre.192.168.0.240.nip.io
      paths:
        - path: /
          # Ignored if not kubeVersion >= 1.14-0
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  config:
    enabled: false
    emptyDir: false

  books:
    enabled: true
    emptyDir: false
    mountPath: /books
    # storageClass: "-"
    existingClaim: "media-ssd-claim"
    accessMode: ReadWriteOnce
    size: 10Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
